### ISSUE TITLE
webpack@5.0.0-beta.28 Cannot find plugin "karma-webpack"

### ISSUE THREAD

**Issue by Xezed** [ryanclark/karma-webpack#450]
- Operating System:
- Node Version: v12.18.3
- NPM Version: v6.14.8
- webpack Version: 5.0.0-beta.28
- karma-webpack Version: 4.0.2

### Expected Behavior

Works fine just like with webpack 4.

### Actual Behavior

```> karma start

17 09 2020 10:09:41.335:ERROR [plugin]: Cannot find plugin "karma-webpack".
  Did you forget to install it?
  npm install karma-webpack --save-dev
17 09 2020 10:09:41.340:ERROR [preprocess]: Can not load "webpack", it is not registered!
  Perhaps you are missing some plugin?
17 09 2020 10:09:41.361:ERROR [karma-server]: Error during file loading or preprocessing
TypeError: process is not a function
    at executeProcessor (/frontend/node_modules/karma/lib/preprocessor.js:47:11)
    at runProcessors (/frontend/node_modules/karma/lib/preprocessor.js:60:23)
    at FileList.preprocess [as _preprocess] (/frontend/node_modules/karma/lib/preprocessor.js:134:11)
    at async Promise.all (index 0)
    at async /frontend/node_modules/karma/lib/file-list.js:90:11
    at async Promise.all (index 8)
17 09 2020 10:09:41.376:ERROR [karma-server]: Error: Found 2 load errors
    at Server.<anonymous> (/frontend/node_modules/karma/lib/server.js:213:27)
    at Object.onceWrapper (events.js:421:28)
    at Server.emit (events.js:327:22)
    at emitListeningNT (net.js:1347:10)
    at processTicksAndRejections (internal/process/task_queues.js:83:21)
npm ERR! Test failed.  See above for more details.
```

### Code

```
var webpack = require('webpack');
var path = require('path');

module.exports = function (config) {
  config.set({
    basePath: '',
    browsers: ['PhantomJS'],
    browserNoActivityTimeout: 30000,
    singleRun: false,
    frameworks: ['es6-shim', 'mocha', 'chai'],
    files: [
      'tests.webpack.js'
    ],
    plugins: [
      'karma-mocha',
      'karma-chai',
      'karma-spec-reporter',
      'karma-phantomjs-launcher',
      'karma-babel-preprocessor',
      'karma-sourcemap-loader',
      'karma-es6-shim',
      'karma-webpack',
    ],
    preprocessors: {
      'tests.webpack.js': ['webpack', 'sourcemap']
    },
    reporters: ['spec'],
    specReporter: {
      suppressErrorSummary: true,  // do not print error summary
      suppressFailed: false,  // do not print information about failed tests
      suppressPassed: false,  // do not print information about passed tests
      suppressSkipped: true,  // do not print information about skipped tests
      showSpecTiming: false // print the time elapsed for each spec
    },
//    reporters: ['dots', 'coverage'],
    coverageReporter: {
      type: 'html',
      dir: 'coverage/',
      instrumenterOptions: {
        istanbul: { noCompact: true }
      }
    },
    logLevel: config.LOG_ERROR,
    client: {
      captureConsole: true, // set to true to be able to debug tests
    },
    webpack: {
      devtool: 'inline-source-map',
      module: {
        rules: [
          {
            test: /\.jsx?$/,
            use: {
              loader: 'babel-loader',
              options: {
                plugins: ['transform-object-rest-spread']
              }
            },
            exclude: /(node_modules|bower_components)/,
          },
        ]
      },
      resolve: {
        modules: [path.resolve('./src'), 'node_modules'],
        extensions: ['.js', '.jsx']
      },
      watch: true,
      plugins: [
        new webpack.LoaderOptionsPlugin({
          babel: {
            presets: ['react', 'es2015', 'airbnb'],
            plugins: ['istanbul']
          }
        }),
        new webpack.ProvidePlugin({
          $: 'jquery',
          jQuery: 'jquery'
        })
      ],
      externals: {
        'cheerio': 'window',
        'react/addons': true,
        'react/lib/ExecutionEnvironment': true,
        'react/lib/ReactContext': true
      }
    },
    webpackServer: {
      noInfo: true
    }
  });
};
```

The very same config works just fine with webpack 4.

**Comment by ryanclark** [comment]
Thank you! I’ve put a note to test this out tomorrow and provide a fix

**Comment by Xezed** [comment]
Just a gentle follow up.
Any luck with it? :)

**Comment by pomek** [comment]
@Xezed, try to install the latest alpha version of the `karma-webpack` package:

```json
{
	"karma-webpack": "^5.0.0-alpha.3.0"
}
```

It helped to me. I know, using the alpha version is risky but as for now, I don't have any other ideas.

**Comment by Xezed** [comment]
@pomek Thank you for reply :) But I remember that I tried it and it didn't work.

**Comment by thijstriemstra** [comment]
> But I remember that I tried it and it didn't work.

Works here, thanks for suggestion @pomek

**Comment by Xezed** [comment]
@thijstriemstra yep I've recalled that I was getting the same one with alpha version

**Comment by thijstriemstra** [comment]
> Thank you! I’ve put a note to test this out tomorrow and provide a fix

Anything we can help with @ryanclark?

**Comment by charklewis** [comment]
Are there any updates on this? I currently have the below config and have the following error:

```
10 11 2020 18:37:29.834:ERROR [karma-server]: Error: Found 2 load errors
    at Server.<anonymous> (/projectl/node_modules/karma/lib/server.js:182:27)
    at Object.onceWrapper (events.js:421:28)
    at Server.emit (events.js:327:22)
    at emitListeningNT (net.js:1347:10)
    at processTicksAndRejections (internal/process/task_queues.js:83:21)
```

Config 
```
/* eslint-env node */

module.exports = function (config) {
  config.set({
    frameworks: ["jasmine"],
    plugins: [
      "karma-jasmine",
      "karma-webpack",
      "karma-chrome-launcher",
      "karma-coverage",
    ],
    files: ["tests/index.test.js"],
    preprocessors: {
      "tests/index.tests.js": ["webpack"],
      "tests/**/*.test.js": ["webpack"],
    },
    reporters: ["progress", "coverage"],
    webpack: {
      mode: "development",
      module: {
        rules: [
          {
            test: /\.less$/,
            loader: "null-loader",
          },
        ],
      },
    },
    coverageReporter: {
      dir: "tests/coverage/",
      reporters: [
        { type: "html", subdir: "report-html" },
        { type: "lcov", subdir: "report-lcov" },
      ],
    },
    port: 9876,
    colors: true,
    logLevel: config.LOG_INFO,
    autoWatch: false,
    browsers: ["ChromeHeadless"],
    singleRun: true,
  });
};
```

Package json 
```
"karma": "^3.1.1",
"karma-chrome-launcher": "^3.1.0",
"karma-coverage": "^1.1.2",
"karma-jasmine": "^1.1.2",
"karma-webpack": "dev",
"webpack": "^5.3.0",
```

**Comment by thijstriemstra** [comment]
@charklewis try adding `webpack` to `frameworks: ["jasmine"],`:

```js
frameworks: ["jasmine", "webpack"],
```

**Comment by charklewis** [comment]
@thijstriemstra I have tried and received a similar error:

```
11 11 2020 09:46:37.917:ERROR [plugin]: Cannot find plugin "karma-webpack".
  Did you forget to install it?
  npm install karma-webpack --save-dev
11 11 2020 09:46:38.089:ERROR [preprocess]: Can not load "webpack", it is not registered!
  Perhaps you are missing some plugin?
11 11 2020 09:46:38.091:ERROR [karma-server]: Server start failed on port 9876: Error: No provider for "framework:webpack"! (Resolving: framework:webpack)
error Command failed with signal "SIGINT".
```

I updated the prior error I was getting in this https://github.com/ryanclark/karma-webpack/issues/450#issuecomment-724890013 - I missed a couple of lines.

**Comment by thijstriemstra** [comment]
@charklewis in combination with:

```
"karma-webpack": "^5.0.0-alpha.3.0"
```

**Comment by charklewis** [comment]
That's correct, I have verified the correct version is installed in the node_modules also:

```
"name": "karma-webpack",
"version": "5.0.0-alpha.3.0",
```

**Comment by codymikol** [comment]
@charklewis I'm having the exact same issue with a very similar karma configuration.

**Comment by charklewis** [comment]
I eventually switched back to use karma and gulp so didn't personally find a solution to this.

**Comment by codymikol** [comment]
@Xezed @charklewis @thijstriemstra 

Just want to check in with you all to see if you've gotten things working. If not, have you made sure of the following.

- karma-webpack is at version 5.0.0-alpha.5
- your specified webpack config has no entry field
- it should also not have an outputs field

**Comment by charklewis** [comment]
@codymikol thanks for the follow up. I have since then gone back to using `gulp` so didn't manage to resolve the web pack issue. When I come to revisit this sometime in the future I'll keep these tips in mind!

**Comment by codymikol** [comment]
I believe that all of the above issues have been addressed either by documentation or in code for the time being. If anyone here is still having issues after following my advice above, I can reopen this issue.
